#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potCB,          sensorPotentiometer)
#pragma config(Sensor, in2,    potArm,         sensorPotentiometer)
#pragma config(Sensor, in3,    Battery,        sensorAnalog)
#pragma config(Sensor, I2C_1,  DL,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  DR,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           MG,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           DriveL,        tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           ArmL1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ArmL2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           CB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ArmR1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           ArmR2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           DriveR,        tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

#pragma platform(VEX2)
#pragma competitionControl(Competition)


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                                LCD Related                                */
/*                                                                           */
/*---------------------------------------------------------------------------*/

int autoMode = 0;
const string autoNames[] =
{
	"Left Three 20pt",
	"Right Three 20pt",
	"Left Three 10pt",
	"Right Three 10pt",
	"Left Three 5pt",
	"Right Three 5pt",
	"defence"
};

#include "LCDDisplay.c"
#include "New_Competition_Includes.c"


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                        Basic Functions & Includes                         */
/*                                                                           */
/*---------------------------------------------------------------------------*/

#define CONE_HOLD 20
#define ARM_HOLD 15
#define CB_HOLD 15

void drive (int powerL, int powerR)
{
	motor[DriveL] = powerL;
	motor[DriveR] = powerR;
}

void ArmPower (int power)
{
	motor[ArmL1] = motor[ArmL2] = motor[ArmR1] = motor [ArmR2] = power;
}

void CBPower (int power)
{
	motor[CB] = power;
}

void mobogo (int power)
{
	motor[MG] = power;
}

void cone (int power)
{
	motor[Intake] = power;
}


#include "DriveAutoFunctions.c"
#include "ArmFunctions.c"
#include "New-ChainBarFunctions.c"
#include "AutoL.c"
#include "AutoR.c"


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	bStopTasksBetweenModes = true;
	bLCDBacklight = true;
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	switch(autoMode)
	{
	case 0:
		break;
	default:
		break;
	}

}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	//clearDebugStream();
	startTask(driverLCD);
	while (true)
	{
		// Right joystick drive
		if ( abs(vexRT[Ch2]) < 10 && abs(vexRT[Ch1]) < 10 )
			drive(0,0);
		else
			drive(vexRT[Ch2] + vexRT[Ch1], vexRT[Ch2] - vexRT[Ch1]);


		// Mobile goal on right buttons
		if (vexRT[Btn8U])
			mobogo(127);
		else if (vexRT[Btn8D])
			mobogo(-127);
		else
			mobogo(0);


		// Manual arm on left triggers
		if (vexRT[Btn5U])
			ArmPower(127);
		else if (vexRT[Btn5D])
			ArmPower(-127);
		else
			ArmPower(ARM_HOLD);


		// Manual chain bar on right triggers
		if (vexRT[Btn6U])
			CBPower(127);
		else if (vexRT[Btn6D])
			CBPower(-127);
		else
			CBPower(CB_HOLD);


		// Intake on left joystick
		if(abs(vexRT[Ch3]) > 15)
			cone(vexRT[Ch3]);
		else
			cone(CONE_HOLD);

	}
}
